task_name_dict = {
    '日常抽奖': 'ri_chang_chou_jiang',
    '混沌灵塔': 'hun_dun_ling_ta', 
    '小助手': 'assistant', 
    '报名': 'bao_ming', 
    '红包': 'hong_bao', 
    '拜谒': 'bai_ye',
    '游历': 'youli', 
    '双修': 'shuangxiu', 
    '挑战仙缘': 'tiao_zhan_xian_yuan', 
    '灵兽': 'ling_shou',
    '副本': 'fuben',
    '坠魔谷': 'zhui_mo_gu', 
    '修炼': 'xiu_lian', 
    '奇袭魔界': 'qi_xi_mo_jie', 
    '论道': 'lun_dao', 
    '兽渊探秘': 'shou_yuan_tan_mi',
    '魔道入侵': 'mo_dao_ru_qing', 
    '虚天殿': 'xu_tian_dian',
    '仙盟争霸': 'xian_meng_zheng_ba', 
    '爬天梯': 'pa_tian_ti',
    '百族供奉': 'bai_zu_gong_feng',
}

task_info_name_dict = {
    '职业': 'profession_name',
    '位面': 'wei_mian',
    '日常抽奖': 'chou_jiang_event',
    '混沌灵塔': 'ling_ta_name',
    '拜谒': 'bai_ye_event_name',
    '拜谒法则': 'bai_ye_fa_ze_level',
    '双修功法': 'shuangxiu_gongfashu_name',
    '挑战仙缘': 'tiao_zhan_xian_yuan_role_name',
    '仙缘位面': 'xian_yuan_wei_mian',
    '游历地点': 'youli_place_name',
    '游历购买次数': 'youli_buy_times',
    '灵兽购买次数': 'ling_shou_buy_times',
    '灵兽囤次数': 'ling_shou_to_save_times',
    '副本': 'fuben_name',
    '副本购买次数': 'fuben_buy_times',
    '百族供奉': 'bai_zu_gong_feng_buy_times',
    '坠魔谷首领': 'zhui_mo_gu_max_level',
    '首领位面': 'shou_ling_wei_mian',
    '修炼购买次数': 'xiu_lian_buy_times',
    '论道': 'dao_chang_level',
    '兽渊探秘': 'shou_yuan_tan_mi_server_nums',
    '魔道入侵': 'mo_dao_ru_qing_server_nums',
    '虚天殿': 'xu_tian_dian_server_nums',
}